-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) YEAR,
       MONTH(OS.SALES_DATE) MONTH,
       COUNT(DISTINCT OS.USER_ID) PUCHASED_USERS,
       ROUND(COUNT(DISTINCT OS.USER_ID)/(
             SELECT COUNT(USER_ID)
             FROM USER_INFO
             WHERE YEAR(JOINED) = '2021'), 1) PUCHASED_RATIO
FROM USER_INFO UI
JOIN ONLINE_SALE OS
USING(USER_ID)
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;