-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW R
USING(MEMBER_ID)
WHERE MP.MEMBER_ID =
(SELECT MEMBER_ID FROM REST_REVIEW
 GROUP BY MEMBER_ID
 ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;